name: Package test

on:
  push:
    branches:
      - master
jobs:
  pytest:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: 3.11
      - run: python -m pip install pytest
      - run: python -m pip .
      - run: pytest tests
